version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    # conflicting/cover same issues
    - forcetypeassert # covered by errcheck
    - lll # covered outside of golangci-lint (by golines)

    - gocritic
    - depguard
    - funlen
    - exhaustruct
    - gochecknoglobals
    - err113
    - nlreturn
    - paralleltest
    - testpackage
    - varnamelen
    - wsl
    # premature optimisation that creates inconsistent code (sometimes Sprintf, sometimes string concatenation)
    # consider enabling _if_ you've profiled performance _and_ Sprintf calls are slowing you down
    - perfsprint
    # the default forbidden list is a bit annoying, especially for debugging: let me Println if I want do
    - forbidigo
    # magic numbers are too subjective for a simple linter
    - mnd
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    errorlint:
      errorf: false
    nolintlint:
      require-specific: true
    revive:
      rules:
        - name: exported
          disabled: true
        - name: context-as-argument
          disabled: false
    staticcheck:
      checks:
        # ST1006: receiver name should be a reflection of its identity; don't use generic names such as "this" or "self"
        # I disagree with this: https://gitlab.com/matthewhughes/mh-lint/-/tree/main/analyzers/methodreceiverself
        - -ST1006
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
