name: PR Checks
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go_version:
          - "1.23"
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
      - name: run tests
        run: go test -race -coverprofile coverage.out ./...
      - name: check coverage
        run: |
          go run gitlab.com/matthewhughes/go-cov/cmd/go-cov add-skips coverage.out > go-cov.out
          go run gitlab.com/matthewhughes/go-cov/cmd/go-cov report --fail-under 100 go-cov.out
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
